"""remove category from uth

Revision ID: 7b67888da7d3
Revises: 
Create Date: 2020-06-27 00:34:30.786779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b67888da7d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'count_book',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('author', 'gender',
               existing_type=sa.CHAR(length=50),
               nullable=True)
    op.drop_column('author', 'category')
    op.drop_column('book', 'category')
    op.alter_column('category', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('category', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('category', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('book', sa.Column('category', sa.CHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('author', sa.Column('category', sa.CHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('author', 'gender',
               existing_type=sa.CHAR(length=50),
               nullable=False)
    op.alter_column('author', 'count_book',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
